import type { RawSheetEvent } from "@/lib/types";

export const LOCAL_EVENTS: RawSheetEvent[] = [
  {
    id: "paris-01",
    pais: "Franca",
    cidade: "Paris",
    evento: "Torre Eiffel",
    datetime: "2026-06-10T09:00:00",
    checked: "true",
    endereco: "Champ de Mars, 5 Av. Anatole France",
  },
  {
    id: "paris-02",
    pais: "Franca",
    cidade: "Paris",
    evento: "Museu do Louvre",
    datetime: "2026-06-10T11:30:00",
    checked: "true",
    endereco: "Rue de Rivoli, Paris",
  },
  {
    id: "paris-03",
    pais: "Franca",
    cidade: "Paris",
    evento: "Catedral de Notre-Dame",
    datetime: "2026-06-10T14:00:00",
    checked: "false",
    endereco: "6 Parvis Notre-Dame - Pl. Jean-Paul II",
  },
  {
    id: "paris-04",
    pais: "Franca",
    cidade: "Paris",
    evento: "Arco do Triunfo",
    datetime: "2026-06-10T16:30:00",
    checked: "true",
    endereco: "Pl. Charles de Gaulle",
  },
  {
    id: "paris-05",
    pais: "Franca",
    cidade: "Paris",
    evento: "Cruzeiro pelo Rio Sena",
    datetime: "2026-06-10T19:00:00",
    checked: "true",
    endereco: "Port de la Bourdonnais",
  },
  {
    id: "madri-01",
    pais: "Espanha",
    cidade: "Madri",
    evento: "Palacio Real",
    datetime: "2026-06-18T09:30:00",
    checked: "false",
    endereco: "C. de Bailen, s/n, Madrid",
  },
  {
    id: "madri-02",
    pais: "Espanha",
    cidade: "Madri",
    evento: "Museu do Prado",
    datetime: "2026-06-18T12:00:00",
    checked: "true",
    endereco: "C. de Ruiz de Alarcon, 23, Madrid",
  },
  {
    id: "madri-03",
    pais: "Espanha",
    cidade: "Madri",
    evento: "Parque do Retiro",
    datetime: "2026-06-18T15:00:00",
    checked: "false",
    endereco: "Plaza de la Independencia, 7, Madrid",
  },
  {
    id: "madri-04",
    pais: "Espanha",
    cidade: "Madri",
    evento: "Gran Via",
    datetime: "2026-06-18T17:30:00",
    checked: "true",
    endereco: "Gran Via, Madrid",
  },
  {
    id: "madri-05",
    pais: "Espanha",
    cidade: "Madri",
    evento: "Mercado de San Miguel",
    datetime: "2026-06-18T20:00:00",
    checked: "false",
    endereco: "Pl. de San Miguel, s/n, Madrid",
  },
  {
    id: "barcelona-01",
    pais: "Espanha",
    cidade: "Barcelona",
    evento: "Sagrada Familia",
    datetime: "2026-06-24T09:00:00",
    checked: "true",
    endereco: "Carrer de Mallorca, 401, Barcelona",
  },
  {
    id: "barcelona-02",
    pais: "Espanha",
    cidade: "Barcelona",
    evento: "Parque Guell",
    datetime: "2026-06-24T11:00:00",
    checked: "true",
    endereco: "08024 Barcelona",
  },
  {
    id: "barcelona-03",
    pais: "Espanha",
    cidade: "Barcelona",
    evento: "La Rambla",
    datetime: "2026-06-24T14:30:00",
    checked: "true",
    endereco: "La Rambla, Barcelona",
  },
  {
    id: "barcelona-04",
    pais: "Espanha",
    cidade: "Barcelona",
    evento: "Casa Batllo",
    datetime: "2026-06-24T16:30:00",
    checked: "false",
    endereco: "Passeig de Gracia, 43, Barcelona",
  },
  {
    id: "barcelona-05",
    pais: "Espanha",
    cidade: "Barcelona",
    evento: "Bairro Gotico",
    datetime: "2026-06-24T19:00:00",
    checked: "true",
    endereco: "Barri Gotic, Barcelona",
  },
  {
    id: "roma-01",
    pais: "Italia",
    cidade: "Roma",
    evento: "Coliseu",
    datetime: "2026-07-02T08:30:00",
    checked: "true",
    endereco: "Piazza del Colosseo, 1, Roma",
  },
  {
    id: "roma-02",
    pais: "Italia",
    cidade: "Roma",
    evento: "Forum Romano",
    datetime: "2026-07-02T10:30:00",
    checked: "true",
    endereco: "Via della Salara Vecchia, 5/6, Roma",
  },
  {
    id: "roma-03",
    pais: "Italia",
    cidade: "Roma",
    evento: "Fontana di Trevi",
    datetime: "2026-07-02T13:00:00",
    checked: "false",
    endereco: "Piazza di Trevi, Roma",
  },
  {
    id: "roma-04",
    pais: "Italia",
    cidade: "Roma",
    evento: "Piazza Navona",
    datetime: "2026-07-02T16:00:00",
    checked: "true",
    endereco: "Piazza Navona, Roma",
  },
  {
    id: "roma-05",
    pais: "Italia",
    cidade: "Roma",
    evento: "Trastevere",
    datetime: "2026-07-02T19:30:00",
    checked: "true",
    endereco: "Trastevere, Roma",
  },
];
